[build]
  command = "chmod +x ./setup-git.sh && rm -f package-lock.json && ./setup-git.sh && npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--loglevel=verbose"