[build]
  command = "npm config set //bitbucket.org/:_password=${BITBUCKET_APP_PASSWORD} && npm config set //bitbucket.org/:username=${BITBUCKET_USERNAME} && npm install && npm run build"
  publish = "dist"